### PR TITLE
Reskin site for MC YSWS

### PR DESCRIPTION
**Pull request by DillonB07**

### CODE REVIEW

**Comment by DillonB07** [comment]
screenshot of the site
image

**Review by GalaxyGamingBoy — APPROVED** [review]
LGTM :)

**Comment by pizzalover125** [comment]
Looks great :)!

**Comment by pizzalover125** [comment]
Maybe make the Hack Club logo bigger.

**Comment by PonderSlime** [comment]
⬆️

**Comment by PonderSlime** [comment]
i agree

**Comment by DillonB07** [comment]
It doesn't look as small when it's live - the scale just feels a bit strange in the screenshot.

**Pull request merged**
